language: php
sudo: false
dist: trusty

addons:
  apt:
    update: true
    packages:
      - python-sphinx
      - python-babel
      - doxygen
      - graphviz

notifications:
  email: false

php:
  - 7

script:
  - export COMMIT_DESC=`git describe --exact 2>/dev/null || git rev-parse --abbrev-ref HEAD`
  - cd docs/src/ && for builder in html latexpdf; do for lang in fr en; do sphinx-build -T -E -b $builder -d ../_build/doctrees -D language=$lang . "../enduser/$builder/$lang/$COMMIT_DESC"; done; done

deploy:
  local-dir: docs/enduser/
  provider: pages
  #repo: Erebot/erebot.github.io
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  on:
    branch: master
