language: php
sudo: false
dist: trusty

addons:
  apt:
    update: true
    packages:
      - python-sphinx
      - python-babel
      - doxygen
      - graphviz
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-lang-french
      - texlive-lang-english

notifications:
  email: false

php:
  - 7

script:
  - rm composer.lock
  - composer self-update -n
  - composer install -n
  - export GHPAGES=`mktemp -d -p "docs/"`
  - export DEFAULT_BRANCH=`git symbolic-ref --short refs/remotes/origin/HEAD | cut -d/ -f2-`
  - git clone --branch=gh-pages https://github.com/${TRAVIS_REPO_SLUG}.git "$GHPAGES/"
  - rm -rf "$GHPAGES/.git"
  - cd docs/src/
  - for lang in fr en; do for builder in html latex; do rm -rf "../../$GHPAGES/refs/${TRAVIS_BRANCH}/$lang/$builder/"; sphinx-build -T -E -b $builder -d ../_build/doctrees -D language=$lang . "../../$GHPAGES/refs/${TRAVIS_BRANCH}/$lang/$builder"; done; make -C "../../$GHPAGES/refs/${TRAVIS_BRANCH}/$lang/latex/" all-pdf < /dev/null; find "../../$GHPAGES/refs/${TRAVIS_BRANCH}/$lang/latex/" ! -name "*.pdf"; done
  - cd ../..
  - if [ -n "$TRAVIS_TAG" ]; then ln -sfT "refs/${TRAVIS_BRANCH}" "$GHPAGES/stable"; else ln -sfT "refs/${TRAVIS_BRANCH}" "$GHPAGES/latest"; fi
  - touch "$GHPAGES/.nojekyll"
  - printf "%s" '<html><head><meta http-equiv="refresh" content="0; url=latest/en/html/"/></head><body onload="window.location.replace('"'"'latest/en/html/'"'"');"></body></html>' > "$GHPAGES/index.html"

deploy:
  local-dir: $GHPAGES
  provider: pages
  #repo: Erebot/erebot.github.io
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  on:
    branch: master
