language: php
sudo: false
dist: trusty

addons:
  apt:
    update: true
    packages:
      - python-sphinx
      - python-babel
      - doxygen

notifications:
  email: false

php:
  - 7

script:
  - cd docs/src/ && sphinx-build -T -E -b html -d _build/doctrees -D language=en . _build/html

#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN
#  keep-history: true
#  verbose: true
#  on:
#    branch: master
