test: Erebot\Module\Admin Class Reference
Erebot\Module\Admin Class Reference
A module that provides several commands intended for administrators.
Public Member Functions
getHelp (\Erebot\Interfaces\Event\Base\TextMessage $event,\Erebot\Interfaces\TextWrapper $words)
handleDeHalfOp (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\ChanText $event)
handleDeOp (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\ChanText $event)
handleDeOwner (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\ChanText $event)
handleDeProtect (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\ChanText $event)
handleDeVoice (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\ChanText $event)
handleHalfOp (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\ChanText $event)
handleJoin (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\Base\TextMessage $event)
handleOp (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\ChanText $event)
handleOwner (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\ChanText $event)
handlePart (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\Base\TextMessage $event)
handleProtect (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\ChanText $event)
handleQuit (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\Base\TextMessage $event)
handleReload (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\Base\TextMessage $event)
handleVoice (\Erebot\Interfaces\EventHandler $handler,\Erebot\Interfaces\Event\ChanText $event)
reload ($flags)
Protected Member Functions
isAdmin (\Erebot\Identity $identity)
setMode (\Erebot\Interfaces\Event\Base\TextMessage $event, $mode)
Protected Attributes
$admins
List of administrators.
$handlers
A list of handlers registered by this module.
$triggers
A list of triggers registered by this module.
Detailed Description
A module that provides several commands intended for administrators.
Definition at line 26 of file Admin.php.
Member Function Documentation
Erebot\Module\Admin::getHelp (\Erebot\Interfaces\Event\Base\TextMessage $event, \Erebot\Interfaces\TextWrapper $words)
Provides help about this module.
Parameters
Erebot::Interfaces::Event::Base_TextMessage $event Some help request.
Erebot::Interfaces::TextWrapper $words Parameters passed with the request. This is the same as this module's name when help is requested on the module itself (in opposition with help on a specific command provided by the module).
Definition at line 192 of file Admin.php.
Erebot\Module\Admin::handleDeHalfOp (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\ChanText $event)
Handles a request to take the half-operator status from someone (-h).
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::TextMessage $event Request to remove the half-operator status from someone.
(PHPMD.UnusedFormalParameter)
Definition at line 525 of file Admin.php.
References Erebot\Module\Admin\setMode().
Erebot\Module\Admin::handleDeOp (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\ChanText $event)
Handles a request to take the operator status from someone (-o).
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::TextMessage $event Request to remove the operator status from someone.
(PHPMD.UnusedFormalParameter)
Definition at line 564 of file Admin.php.
References Erebot\Module\Admin\setMode().
Erebot\Module\Admin::handleDeOwner (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\ChanText $event)
Handles a request to take the owner status from someone (-q).
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::TextMessage $event Request to remove the owner status from someone.
(PHPMD.UnusedFormalParameter)
Definition at line 643 of file Admin.php.
References Erebot\Module\Admin\setMode().
Erebot\Module\Admin::handleDeProtect (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\ChanText $event)
Handles a request to take the protected status from someone (-a).
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::TextMessage $event Request to remove the protected status from someone.
(PHPMD.UnusedFormalParameter)
Definition at line 603 of file Admin.php.
References Erebot\Module\Admin\setMode().
Erebot\Module\Admin::handleDeVoice (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\ChanText $event)
Handles a request to take the voice status from someone (-v).
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::TextMessage $event Request to remove the voice status from someone.
(PHPMD.UnusedFormalParameter)
Definition at line 485 of file Admin.php.
References Erebot\Module\Admin\setMode().
Erebot\Module\Admin::handleHalfOp (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\ChanText $event)
Handles a request to give someone the half-operator status (+h).
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::TextMessage $event Request to give someone the half-operator status.
(PHPMD.UnusedFormalParameter)
Definition at line 504 of file Admin.php.
References Erebot\Module\Admin\setMode().
Erebot\Module\Admin::handleJoin (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\Base\TextMessage $event)
Handles a request to join some IRC channel.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::TextMessage $event Request to join the IRC channel with the given name (passed as an additional parameter).
(PHPMD.UnusedFormalParameter)
Definition at line 663 of file Admin.php.
References Erebot\Module\Admin\isAdmin().
Erebot\Module\Admin::handleOp (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\ChanText $event)
Handles a request to give someone the operator status (+o).
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::TextMessage $event Request to give someone the operator status.
(PHPMD.UnusedFormalParameter)
Definition at line 545 of file Admin.php.
References Erebot\Module\Admin\setMode().
Erebot\Module\Admin::handleOwner (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\ChanText $event)
Handles a request to give someone the owner status (+q).
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::TextMessage $event Request to give someone the owner status.
(PHPMD.UnusedFormalParameter)
Definition at line 623 of file Admin.php.
References Erebot\Module\Admin\setMode().
Erebot\Module\Admin::handlePart (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\Base\TextMessage $event)
Handles a request to make the bot leave an IRC channel.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::TextMessage $event Request to make the bot leave an IRC channel. The request may contain the name of the IRC channel to leave or "*" to make it leave all channels the bot is currently on. If missing, the current channel will be left. You may also pass some message that will be displayed to other users when leaving the channel.
(PHPMD.UnusedFormalParameter)
Definition at line 280 of file Admin.php.
References Erebot\Module\Admin\isAdmin().
Erebot\Module\Admin::handleProtect (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\ChanText $event)
Handles a request to give someone the protected status (+a).
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::TextMessage $event Request to give someone the protected status.
(PHPMD.UnusedFormalParameter)
Definition at line 583 of file Admin.php.
References Erebot\Module\Admin\setMode().
Erebot\Module\Admin::handleQuit (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\Base\TextMessage $event)
Handles a request to make the bot disconnect from the current server.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::TextMessage $event Request to make the bot disconnect from the current IRC server. You may pass a message that will be used as the quit message.
(PHPMD.UnusedFormalParameter)
Definition at line 329 of file Admin.php.
References Erebot\Module\Admin\isAdmin().
Erebot\Module\Admin::handleReload (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\Base\TextMessage $event)
Handles a request to reload the bot's modules.
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::TextMessage $event Request to reload all modules used by the bot.
(PHPMD.UnusedFormalParameter)
Definition at line 687 of file Admin.php.
References Erebot\Module\Admin\isAdmin().
Erebot\Module\Admin::handleVoice (\Erebot\Interfaces\EventHandler $handler, \Erebot\Interfaces\Event\ChanText $event)
Handles a request to give someone the voice status (+v).
Parameters
Erebot::Interfaces::EventHandler $handler Handler that triggered this event.
Erebot::Interfaces::Event::Base::TextMessage $event Request to give someone the voice status.
(PHPMD.UnusedFormalParameter)
Definition at line 466 of file Admin.php.
References Erebot\Module\Admin\setMode().
Erebot\Module\Admin::isAdmin (\Erebot\Identity $identity) protected
Tests whether the given identity refers to an administrator or not.
Parameters
Erebot::Identity $identity Identity to test.
Return values
bool true if the given identity refers to an administrator, false otherwise.
Definition at line 229 of file Admin.php.
Referenced by Erebot\Module\Admin\handleJoin(), Erebot\Module\Admin\handlePart(), Erebot\Module\Admin\handleQuit(), Erebot\Module\Admin\handleReload(), and Erebot\Module\Admin\setMode().
Erebot\Module\Admin::reload ($flags)
This method is called whenever the module is (re)loaded.
Parameters
int $flags A bitwise OR of the Erebot::Module::Base::RELOAD_* constants. Your method should take proper actions depending on the value of those flags.
Note
See the documentation on individual RELOAD_* constants for a list of possible values.
Definition at line 49 of file Admin.php.
References Erebot\Module\Admin\$triggers.
Erebot\Module\Admin::setMode (\Erebot\Interfaces\Event\Base\TextMessage $event, $mode) protected
Adds or removes a channel status for some user on some IRC channel.
Parameters
Erebot::Interfaces::Event::Base::TextMessage $event The original request to add or remove a channel status from some user.
string $mode A string describing the type of change to apply. ie. something like "+v" (voice) or "-o" (deop).
Definition at line 370 of file Admin.php.
References Erebot\Module\Admin\isAdmin().
Referenced by Erebot\Module\Admin\handleDeHalfOp(), Erebot\Module\Admin\handleDeOp(), Erebot\Module\Admin\handleDeOwner(), Erebot\Module\Admin\handleDeProtect(), Erebot\Module\Admin\handleDeVoice(), Erebot\Module\Admin\handleHalfOp(), Erebot\Module\Admin\handleOp(), Erebot\Module\Admin\handleOwner(), Erebot\Module\Admin\handleProtect(), and Erebot\Module\Admin\handleVoice().
The documentation for this class was generated from the following file:
src/Admin.php